AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-chatgpt-app

  Sample SAM Template for serverless-chatgpt-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  ChatgptHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          ORGANIZAION_ID: "org-wQZNR8qyaxUxWJkjRFriV5rr"
          OPEN_AI_API_KEY: "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"
      Architectures:
      - x86_64
      Events:
        ListModels:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /model
            Method: get
        CreateQuestion:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ListModelsApi:
    Description: API Gateway endpoint URL for Prod stage for models of chat gpt
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/model/"
  CreateQuestionApi:
    Description: API Gateway endpoint URL for chat gpt message
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
  ChatgptHandlerFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt ChatgptHandlerFunction.Arn
  ChatgptHandlerFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ChatgptHandlerFunctionRole.Arn
